"""initial_schema_all_models

Revision ID: 2e9fe1e0f0ff
Revises: 
Create Date: 2026-09-27 00:45:32.758966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2e9fe1e0f0ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fen', sa.String(), nullable=False),
    sa.Column('moves', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rating_deviation', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('themes', sa.String(), nullable=False),
    sa.Column('game_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_puzzle_rating', 'puzzles', ['rating'], unique=False)
    op.create_table('users',
    sa.Column('role', sa.Enum('STUDENT', 'COACH', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('elo_rating', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('tournaments_played', sa.Integer(), nullable=False),
    sa.Column('tournaments_won', sa.Integer(), nullable=False),
    sa.Column('tournaments_podium', sa.Integer(), nullable=False),
    sa.Column('lichess_username', sa.String(length=50), nullable=True),
    sa.Column('lichess_blitz_rating', sa.Integer(), nullable=True),
    sa.Column('lichess_rapid_rating', sa.Integer(), nullable=True),
    sa.Column('lichess_puzzle_rating', sa.Integer(), nullable=True),
    sa.Column('lichess_verification_code', sa.String(length=32), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_lichess_username'), 'users', ['lichess_username'], unique=False)
    op.create_table('clans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tag', sa.String(length=6), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leader_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clans_name'), 'clans', ['name'], unique=True)
    op.create_index(op.f('ix_clans_tag'), 'clans', ['tag'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'PLAYER_WON', 'BOT_WON', 'DRAW', 'RESIGNED', name='gamestatus'), nullable=False),
    sa.Column('player_color', sa.Enum('WHITE', 'BLACK', name='playercolor'), nullable=False),
    sa.Column('bot_difficulty', sa.Integer(), nullable=False),
    sa.Column('current_fen', sa.String(), nullable=False),
    sa.Column('moves_uci', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_status'), 'games', ['status'], unique=False)
    op.create_index(op.f('ix_games_user_id'), 'games', ['user_id'], unique=False)
    op.create_table('user_solved_puzzles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('puzzle_id', sa.String(), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'puzzle_id')
    )
    op.create_table('clan_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('LEADER', 'OFFICER', 'MEMBER', name='clanrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clan_id', 'user_id', name='uq_clan_member'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clan_members')
    op.drop_table('user_solved_puzzles')
    op.drop_index(op.f('ix_games_user_id'), table_name='games')
    op.drop_index(op.f('ix_games_status'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_clans_tag'), table_name='clans')
    op.drop_index(op.f('ix_clans_name'), table_name='clans')
    op.drop_table('clans')
    op.drop_index(op.f('ix_users_lichess_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_puzzle_rating', table_name='puzzles')
    op.drop_table('puzzles')
    # ### end Alembic commands ###
